name: Bandit Code Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  security_scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit Scan
        uses: tj-actions/bandit@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
